### ISSUE TITLE
Sugestão para facilitar o andamento do curso para desenvolvedores menos experientes...

### ISSUE THREAD

**Issue by yvesguilherme** [mrtrycatch/EmprestimoLivroCafecombug#1]
Prezado Vinicius, bom dia!
Abaixo deixo o Dockerfile e o docker-compose.yaml que você pode deixar no projeto. Assim quem não tem tanta experiência, pode subir a api localmente e não ter problemas para ter que instalar e rodar o .net local...

Dockerfile
```docker
# Use the official .NET image as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["EmprestimoLivrosNovo.API/EmprestimoLivrosNovo.API.csproj", "EmprestimoLivrosNovo.API/"]
COPY ["EmprestimoLivrosNovo.Application/EmprestimoLivrosNovo.Application.csproj", "EmprestimoLivrosNovo.Application/"]
COPY ["EmprestimoLivrosNovo.Domain/EmprestimoLivrosNovo.Domain.csproj", "EmprestimoLivrosNovo.Domain/"]
COPY ["EmprestimoLivrosNovo.Infra.Data/EmprestimoLivrosNovo.Infra.Data.csproj", "EmprestimoLivrosNovo.Infra.Data/"]
COPY ["EmprestimoLivrosNovo.Infra.Ioc/EmprestimoLivrosNovo.Infra.Ioc.csproj", "EmprestimoLivrosNovo.Infra.Ioc/"]
RUN dotnet restore "EmprestimoLivrosNovo.API/EmprestimoLivrosNovo.API.csproj"
COPY . .
WORKDIR "/src/EmprestimoLivrosNovo.API"
RUN dotnet build "EmprestimoLivrosNovo.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EmprestimoLivrosNovo.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EmprestimoLivrosNovo.API.dll"]
```

docker-compose.yaml
```yaml
version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cafecombug
      POSTGRES_DB: EmprestimoLivro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  emprestimoapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=cafecombug;Host=db;Port=5432;Database=EmprestimoLivro;Pooling=true;Connection Lifetime=0;
    depends_on:
      - db

volumes:
  postgres_data:
```

#### comando para subir localmente (necessário ter o docker e o docker-compose na máquina)
```bash
docker-compose up --build
```
